version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: .
    command: uvicorn agent.trip_agent_server:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./:/app # Mount current directory for development reload
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0 # Use service name 'redis' for connection
      - REDIS_SSL_ENABLED=false # Explicitly disable SSL for Redis in Docker
      # API Keys can be loaded from .env via env_file, or overridden here
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_PLACE_API_KEY=${GOOGLE_PLACE_API_KEY}
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build: .
    command: python gradio_app.py --server-name 0.0.0.0 --server-port 7860
    volumes:
      - ./:/app # Mount current directory for development reload
    ports:
      - "7860:7860"
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://backend:8001 # Use service name 'backend'
      - REDIS_SSL_ENABLED=false # Explicitly disable SSL for Redis in Docker
      # Gradio settings can be loaded from .env or set here
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    depends_on:
      - backend
    restart: unless-stopped
